
export enum Provider {
    STORAGE = "STORAGE",
    AUTH = "AUTH",
    HTTP_CLIENT = "HTTP_CLIENT",
    QUEUE_PRODUCER = "QUEUE_PRODUCER",
    MESSAGE_REPOSITORY = "MESSAGE_REPOSITORY",
    INSTANCE_REPOSITORY = "INSTANCE_REPOSITORY",
    WEBHOOK_REPOSITORY = "WEBHOOK_REPOSITORY",
    AUTH_CREDENTIAL_REPOSITORY = "AUTH_CREDENTIAL_REPOSITORY",
    NOTIFY_THIRD_APPLICATION_VIA_WEBHOOK_REPOSITORY = "NOTIFY_THIRD_APPLICATION_VIA_WEBHOOK_REPOSITORY",
}