
export enum Provider {
    STORAGE = "STORAGE",
    AUTH = "AUTH",
    QUEUE_PRODUCER = "QUEUE_PRODUCER",
    MESSAGE_REPOSITORY = "MESSAGE_REPOSITORY",
    INSTANCE_REPOSITORY = "INSTANCE_REPOSITORY"
}